### ISSUE TITLE
aberrent coverage script

### ISSUE THREAD

**Issue by sarah872** [shelbirussell/Russell-et-al-2018#1]
When running the script
```
perl SMD_workflow/scripts/find_aberrant_regions.pl sample_coverage_by_site.txt

```
I am getting the following error:
```
Illegal division by zero at SMD_workflow/scripts/find_aberrant_regions.pl line 118.
```
My `sample_coverage_by_site.txt` looks like this:
```
1071200001      1       2
1071200001      2       3
1071200001      3       4
1071200001      4       4
1071200001      5       4
1071200001      6       4
```
Also, I noticed that when running
```
genomeCoverageBed -d -ibam merged.bam -g mygenome.fasta
```
There is a warning saying that the `mygenome.fasta` is not considered if a bam file is provided.

Do you have a solution?
I ran the `genomeCoverageBed` with my genome sequence (not the coding-sequences). Is that right?

**Comment by shelbirussell** [comment]
That error on that line indicates that you have a window size of zero for
some reason.

Yes, you should run genomeCoverageBed with the full genome. The script
find_aberrant_regions.pl uses a window approach to find regions with
abnormal coverage.

Based on that excerpt of your coverage_by_site.txt file, your coverage file
looks correct. However, I'm not sure why you would have gotten that error
about the reference fasta file. I never saw that error when I ran my files
(I just looked back at my output files to check).

Given this information, I'd suggest you check throughout your
coverage_by_site.txt file to make sure you don't have some broken or empty
line somewhere (if genomeCoverageBed created an error somewhere).

Alternatively, is your genome highly fragmented? If your scaffolds are less
than the window size of 1000 bp, I imagine an error like this would be
thrown.

Best,
Shelbi
